apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-fbot
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dvul-tenant/rhtap-demo-app/hacbs-test-project-fbot@sha256:613cdc8bba6148cb48073749d0b0a36ddcd9397b5ae7dd7c786161f6c8e6afa0
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
